---
title: "Ordinal Plots"
author: "Jon Nations"
---
# Ordinal Plots
# Figure 3 and Supporting Figures


```{r}
pacman::p_load(tidyverse, patchwork, brms, here)
scale2 <- function(x, na.rm = TRUE) (x - mean(x, na.rm = na.rm)) / sd(x, na.rm)

here::i_am("Plots/Figures_3_S3_Model_Plots.Rmd")
```

### Plotting Fuctions

#### Fig3 Plot Function
```{r}
ord_plotlj_s <- function(mod, effect, effect2, title){
conditions <- data.frame(log_cuberoot_mass = c(-1.5, 0, 1.5))
conditional_effects({{mod}}, 
                          categorical  = TRUE, 
                          prob = 0.75, 
                          conditions = conditions, 
                          effects= {{effect}})[[1]] %>% 
  as_tibble() %>% 
  mutate(log_cuberoot_mass = factor(log_cuberoot_mass, 
                                    levels = c("-1.5", "0", "1.5"),
                                    labels = c("Low Mass", "Mean Mass", "High Mass"))) %>% 
  rename(Probability = estimate__) %>% 
ggplot(aes(x={{effect2}}, y = Probability, group = cats__)) +
  geom_ribbon(aes(ymin = lower__, 
                  ymax = upper__, 
                  fill = cats__), 
              alpha=0.2) +
  geom_line(size=0.4, 
            #position=position_dodge(0.05), 
            aes(color=cats__)) +
  facet_wrap(~ log_cuberoot_mass, 
             ncol = 3) +
  labs(subtitle = {{title}}) +
  scico::scale_fill_scico_d(palette = "lajolla", 
                            begin  = 0.3, 
                            end = 0.95, 
                            name = "Dietary\nImportance\nRank") +
  scico::scale_color_scico_d(palette = "lajolla", 
                            begin  = 0.3, 
                            end = 0.95, 
                             name = "Dietary\nImportance\nRank") +
  theme_classic() +
  ylim(0, 1) +
  guides(colour = guide_legend(reverse=T,
                               title.theme = element_text(size = 7.5),
                               override.aes = list(size = 1)),
         fill = guide_legend(reverse=T,
                             title.theme = element_text(size = 7.5),
                             override.aes = list(size = 1))) + 
  theme( panel.grid.major = element_blank(), 
         panel.grid.minor = element_blank(),
         strip.background = element_blank(),
         strip.text.x = element_text(size = 6, margin=margin(b=0.9)),
        # strip.text.x = element_text(size = 8),
         panel.border = element_rect(colour = "black", 
                                     fill = NA,
                                     size = rel(0.8)),
         axis.line = element_line(colour = "NA"),
         axis.text.y = element_text(size=rel(0.5)),
         axis.text.x = element_text(size=rel(0.5)),
         axis.ticks = element_line(size = rel(0.25)),
         axis.ticks.length =  unit(0.5, "pt"),
         legend.text=element_text(size=rel(0.7)),
         #legend.spacing.y = unit(-0.001, 'lines'),
         legend.key = element_rect(color = NA),
         legend.key.size =    unit(.95, "lines"),
         axis.title.y = element_text(size = 6, margin=margin(0,-2,0,-10)),
         axis.title.x = element_text(size = 6, margin=margin(0,0,-3,0)),
         plot.subtitle=element_text(size=8, margin=margin(-20,0,3.2,0)),
         legend.box.margin = unit(c(-0.5, 0, 0, 0), "lines"),
         plot.margin = unit(c(0.2, 0, 0.3, 0), "lines")
         )
}
```



## Figure 3


```{r}
ord_plotlj_s(readRDS(here("Code/Models/mod_outputs/bird_md_RLGA.Rds")), 
         "RLGA", RLGA,
         "Bird") -> p1
ord_plotlj_s(readRDS(here("Code/Models/mod_outputs/fruit_ms_OPCR.Rds")), 
         "m2_opcr", m2_opcr,
         "Fruit") + 
  labs(y = "", x = "m2 OPCr") -> p2
ord_plotlj_s(readRDS(here("Code/Models/mod_outputs/herptile_md_DNE.Rds")), 
         "m1_dne", m1_dne,
         "Herptile") + 
  labs(y = "", x = "m1 aDNE") -> p3
ord_plotlj_s(readRDS(here("Code/Models/mod_outputs/large_mammal_ms_RLGA.Rds")), 
         "RLGA", RLGA,
         "Large Mammal")  -> p4
ord_plotlj_s(readRDS(here("Code/Models/mod_outputs/small_mammal_md_RLGA.Rds")), 
         "RLGA", RLGA,
         "Small Mammal")  + 
  labs(y = "") -> p5
ord_plotlj_s(readRDS(here("Code/Models/mod_outputs/soft_invert_mn_DNE.Rds")), 
         "m1_dne", m1_dne,
         "Soft Invertebrate") + 
  labs(y = "", x = "m1 aDNE") -> p6


plot3col <- (p1 + p2 + p3 ) /  (p4 + p5 + p6)  + plot_layout(guides = "collect")  + plot_annotation(tag_levels = 'A') & theme(plot.tag = element_text(size = 10))
plot3col
ggsave(here("Plots", "Figure_3.pdf"), width = 7.5, height = 3.2)
ggsave(here("Plots", "Figure_3.png"), width = 7.5, height = 3.2)
```


### FigS3 Plotting FUnctions

```{r}
ord_plotlj <- function(mod, effect, title){
conditions <- data.frame(log_cuberoot_mass = c(-1.5, 0, 1.5))
mass.labs <- c("Low Mass", "Mean Mass", "High Mass")
names(mass.labs) <- c(-1.5, 0, 1.5)
p1 <- conditional_effects({{mod}}, 
                          categorical  = TRUE, 
                          prob = 0.75, 
                          conditions = conditions, 
                          effects= {{effect}})
plot(p1, plot = FALSE)[[1]] + 
  facet_wrap(~log_cuberoot_mass, 
             ncol = 3,
             labeller = labeller(log_cuberoot_mass = mass.labs)) + 
  labs(subtitle = {{title}}) +
  scico::scale_fill_scico_d(palette = "lajolla", 
                            begin  = 0.3, 
                            end = 0.95, 
                            name = "Dietary\nImportance") +
  scico::scale_color_scico_d(palette = "lajolla", 
                            begin  = 0.3, 
                            end = 0.95, 
                             name = "Dietary\nImportance") +
  theme_classic() + ylim(0, 1) + guides(colour = guide_legend(reverse=T,
                                                  #title.hjust = 0.5,
                                                  title.theme = element_text(size = 8)),
                            fill = guide_legend(reverse=T,
                                                  #title.hjust = 0.5,
                                                  title.theme = element_text(size = 8))) + 
                             theme( panel.grid.major = element_blank(), 
                                    panel.grid.minor = element_blank(),
                                    strip.background = element_blank(),
                                    panel.border = element_rect(colour = "black", 
                                                                fill = NA))
}



ord_plot2lj <- function(mod, effect, title){
conditions <- data.frame(log_cuberoot_mass = c(-1.5, 0, 1.5))
mass.labs <- c("Low Mass", "Mean Mass", "High Mass")
names(mass.labs) <- c(-1.5, 0, 1.5)
p1 <- conditional_effects({{mod}}, 
                          categorical  = TRUE, 
                          prob = 0.75, 
                          conditions = conditions, 
                          effects= {{effect}})
plot(p1, plot = FALSE)[[1]] + 
  facet_wrap(~log_cuberoot_mass, 
             ncol = 3,
             labeller = labeller(log_cuberoot_mass = mass.labs)) + 
  labs(subtitle = {{title}}) +
  scico::scale_fill_scico_d(palette = "lajolla", 
                            begin  = 0.3, 
                            end = 0.73, 
                            name = "Dietary\nImportance") +
  scico::scale_color_scico_d(palette = "lajolla", 
                            begin  = 0.3, 
                            end = 0.73, 
                             name = "Dietary\nImportance") +
  theme_classic() +  guides(colour = guide_legend(reverse=T,
                                                  #title.hjust = 0.5,
                                                  title.theme = element_text(size = 8)),
                            fill = guide_legend(reverse=T,
                                                  #title.hjust = 0.5,
                                                  title.theme = element_text(size = 8))) + 
                             theme( panel.grid.major = element_blank(), 
                                    panel.grid.minor = element_blank(),
                                    strip.background = element_blank(),
                                    panel.border = element_rect(colour = "black", 
                                                                fill = NA),
                                    legend.position = "none")
}
```


#### FigS3 Plots

```{r}

m.bird =     readRDS(here("Code/Models/mod_outputs/bird_md_RLGA.Rds"))
m.carrion =  readRDS(here("Code/Models/mod_outputs/carrion_md_RLGA.Rds"))
m.egg =      readRDS(here("Code/Models/mod_outputs/egg_md_RFI.Rds"))
m.fish =     readRDS(here("Code/Models/mod_outputs/fish_ms_RLGA.Rds"))
m.fruit =    readRDS(here("Code/Models/mod_outputs/fruit_ms_OPCR.Rds"))
m.hard =     readRDS(here("Code/Models/mod_outputs/hard_invert_md_ALL.Rds"))
m.herp =     readRDS(here("Code/Models/mod_outputs/herptile_md_DNE.Rds"))
m.large =    readRDS(here("Code/Models/mod_outputs/large_mammal_ms_RLGA.Rds"))
m.plant =    readRDS(here("Code/Models/mod_outputs/plant_md_DNE.Rds"))
m.root =     readRDS(here("Code/Models/mod_outputs/root_mn_RLGA.Rds"))
m.seed =     readRDS(here("Code/Models/mod_outputs/seed_mn_DNE.Rds"))
m.small =    readRDS(here("Code/Models/mod_outputs/small_mammal_md_RLGA.Rds"))
m.soft =     readRDS(here("Code/Models/mod_outputs/soft_invert_mn_DNE.Rds"))

ord_plotlj(m.bird, "RLGA", "Bird")                             -> p1
ord_plotlj(m.carrion, "RLGA", "Carrion") + labs(y = "")        -> p2
ord_plotlj(m.egg, "RFI_m1", "Egg") + labs(y = "")             -> p3
ord_plotlj(m.egg, "RFI_m2", "Egg")  + labs(y = "")            -> p4
ord_plotlj(m.fish, "RLGA", "Fish")                            -> p5
ord_plotlj(m.fruit, "m1_opcr", "Fruit")  + labs(y = "")        -> p6
ord_plotlj(m.fruit, "m2_opcr", "Fruit")  + labs(y = "")        -> p7
ord_plotlj(m.hard, "m1_dne", "Hard Invert") + labs(y = "")      -> p8
ord_plotlj(m.hard, "m2_dne", "Hard Invert")                     -> p9
ord_plotlj(m.hard, "m1_opcr", "Hard Invert")  + labs(y = "")   -> p10
ord_plotlj(m.hard, "m2_opcr", "Hard Invert") + labs(y = "")    -> p11
ord_plotlj(m.hard, "RFI_m1", "Hard Invert") + labs(y = "")    -> p12
ord_plotlj(m.hard, "RFI_m2", "Hard Invert")                      -> p13
ord_plotlj(m.hard, "RLGA", "Hard Invert")  + labs(y = "")      -> p14
ord_plotlj(m.herp, "m1_dne", "Herptile") + labs(y = "")        -> p15
ord_plotlj(m.herp, "m2_dne", "Herptile")  + labs(y = "")        -> p16
ord_plotlj(m.large, "RLGA", "Large Mammal")                     -> p17
ord_plotlj(m.plant, "m1_dne", "Plant")  + labs(y = "")         -> p18
ord_plotlj(m.plant, "m2_dne", "Plant") + labs(y = "")          -> p19
ord_plot2lj(m.root, "RLGA", "Root")   + labs(y = "")         -> p20
ord_plotlj(m.seed, "m1_dne", "Seed")                         -> p21
ord_plotlj(m.seed, "m2_dne", "Seed") +  labs(y = "")           -> p22
ord_plotlj(m.small, "RLGA", "Small Mammal")  + labs(y = "")    -> p23
ord_plotlj(m.soft, "m1_dne", "Soft Invert")   + labs(y = "")   -> p24
ord_plotlj(m.soft, "m2_dne", "Soft Invert")                  -> p25
plot_spacer() -> p26
plot_spacer() -> p27
plot_spacer() -> p28
```

```{r}

plot <- (p1 | p2 | p3 | p4) / (p5 | p6 | p7 | p8) / (p9 | p10 | p11 | p12)  / (p13 | p14 | p15 | p16) / (p17 | p18 | p19 | p20) / (p21 | p22 | p23 | p24) / (p25 | p26 | p27 | p28) + plot_layout(guides = "collect")  + plot_annotation(caption = 'Tryptic Plots of the model for each food item with the highest model weight. Full Model outputs are in table form in the Supporting Information')
plot
ggsave(here("Plots", "Figure_S_Models.pdf"), width = 17, height = 21)
ggsave(here("Plots", "Figure_S_Models.png"), width = 17, height = 21)
```

